name = "Custom Drag Import"
id = "CustomDragImport"
maintainer = "AIGODLIKE社区, Atticus"
version = "0.3.2"
tagline = "Custom your drag import handle in blender"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["Import-Export"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/atticus-lv/CustomDragImport"
[permissions]
files = "Drag Import File Handle"
clipboard = "Read Files on clipboard (Windows Only) to import"